ARG BASE=secondstate/soll:ubuntu-base
FROM ${BASE}

RUN apt update \
    && apt install -y \
        cmake \
        software-properties-common

RUN wget --quiet -O - https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add - \
    && apt-add-repository 'deb https://deb.nodesource.com/node_10.x xenial main'

RUN apt update \
    && apt install -y \
        nodejs
RUN rm -rf /var/lib/apt/lists/*

RUN npm install -g mocha
