FROM ubuntu:20.04

RUN apt update \
    && apt install -y software-properties-common

RUN apt update \
    && apt install -y \
        llvm-10-dev \
        llvm-10-tools \
        liblld-10-dev \
        cmake \
        make \
        wget \
        python-psutil \
        binaryen

RUN rm -rf /var/lib/apt/lists/*
