#!/bin/bash
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
shopt -s extglob

SOURCE_TYPE=sol
SOURCE_FILES=
TARGET_TYPE=ewasm
VERBOSE=false
BINDIR=

function run
{
    if "$VERBOSE"; then
        echo "RUN $@"
    fi
    bash -c "$@"
}

# Parse arguments
function parse_args
{
    while [ $# -gt 0 ] ; do # Optional [-h|-v]
        case "$1" in
            -h)    ;;
            -v)    VERBOSE=true ;;
            *)     break ;;
        esac
        shift
    done
    while [ $# -gt 0 ] ; do # Optional [sol|yul] (case-insensitive)
        case "${1,,}" in
            sol)   ;;
            yul)   SOURCE_TYPE=yul ;;
            *)     break ;;
        esac
        shift
    done
    while [ $# -gt 0 ] ; do # Optional [ewasm|evm] (case-insensitive)
        case "${1,,}" in
            ewasm) ;;
            evm)   TARGET_TYPE=evm ;;
            *)     break ;;
        esac
        shift
    done
    if [ $# -lt 1 ]; then
        echo "$0 [-h|-v] [sol|yul] [ewasm|evm] <SOURCE_FILES ...>"
        exit 1
    fi
    SOURCE_FILES=$@
}

function env_setup
{
    BINDIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" >& /dev/null && pwd)
}

function source_to_ll
{
    local filename=$1
    case "${SOURCE_TYPE}" in
        sol)
            run "\"${SOLL_PATH}\" \"${filename}\" > \"${filename%%*(.sol)}.ll\""
            ;;
        yul)
            run "\"${SOLL_PATH}\" -lang=Yul \"${filename}\" > \"${filename%%*(.yul)}.ll\""
            ;;
    esac
}

function ll_to_target
{
    local filename=$1
    local prefix=${filename%%*(.ll|.sol|.yul)}
    case "${TARGET_TYPE}" in
        ewasm)
            run "\"${BINDIR}/ll2ewasm_${SOURCE_TYPE}\" -v \"${prefix}.ll\""
            run "test -f \"${prefix}.wasm\""
            ;;
    esac
}

parse_args "$@"
env_setup
if [ ! -z "${SOLL_PATH}" ]; then # backward-compatibility
    for filename in ${SOURCE_FILES[@]}; do source_to_ll "${filename}"; done
fi
for filename in ${SOURCE_FILES[@]}; do ll_to_target "${filename}"; done
