name: build and test SOLL

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_and_test_gcc_debug:
    runs-on: ubuntu-latest
    container:
      image: secondstate/soll:latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup build folder
      run: |
        rm -rf build
        mkdir -p build

    - name: Build SOLL using g++
      run: |
        cd build
        cmake -DCMAKE_BUILD_TYPE=Debug -DSOLL_INCLUDE_TESTS=true ..
        make -j2

    - name: Test SSVM
      run: |
        cd build
        ctest

  build_and_test_gcc_release:
    runs-on: ubuntu-latest
    container:
      image: secondstate/soll:latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup build folder
      run: |
        rm -rf build
        mkdir -p build

    - name: Build SOLL using g++
      run: |
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release -DSOLL_INCLUDE_TESTS=true ..
        make -j2

    - name: Test SSVM
      run: |
        cd build
        ctest

  build_and_test_gcc_debug_coverage:
    runs-on: ubuntu-latest
    container:
      image: secondstate/soll:latest

    steps:
    - uses: actions/checkout@v2

    - name: Install gcovr
      run: |
        apt update
        apt install -y gcovr

    - name: Setup build folder
      run: |
        rm -rf build
        mkdir -p build

    - name: Build SOLL using g++
      run: |
        cd build
        cmake -DCMAKE_BUILD_TYPE=Debug -DSOLL_INCLUDE_TESTS=true -DSOLL_COVERAGE=true ..
        make -j2

    - name: Generate coverage report
      run: |
        cd build
        make -j2 codecov
        wget https://codecov.io/bash -O codecov.bash
        bash codecov.bash -t ${{ secrets.CODECOV_TOKEN }} -X gcov -X coveragepy -X search -X xcode -X gcovout -f codecov.xml
